WINDOW_BORDER_PADDING = 10

MAIN = 'main'
SCREEN = 'screen'
KEYBOARD = 'keyboard'
FILE = 'file'
COPY_FILE = 'copy-file'
REGISTRY = 'reg'
APPLICATION = 'app'
START_APP = 'start-app'
START_CUSTOM_APP = 'start-custom-app'
PROCESS = 'process'
START_PROCESS = 'start-process'

UPDATE_TIME = {}
UPDATE_TIME[MAIN] = 20
UPDATE_TIME[SCREEN] = 200
UPDATE_TIME[KEYBOARD] = 200
UPDATE_TIME[FILE] = 200
UPDATE_TIME[COPY_FILE] = 200
UPDATE_TIME[REGISTRY] = 200
UPDATE_TIME[APPLICATION] = 200
UPDATE_TIME[START_APP] = 200
UPDATE_TIME[START_CUSTOM_APP] = 200
UPDATE_TIME[PROCESS] = 200
UPDATE_TIME[START_PROCESS] = 200

FRAME_WIDTH = 800